local function complete_function(self, message_id, message, sender)
	print(message_id)
end

function init(self)
	
	-- profiler.enable_ui(true)
	-- profiler.set_ui_view_mode(profiler.VIEW_MODE_MINIMIZED)
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })

	rive.play_anim("/go2#rivemodel", "idle", go.PLAYBACK_LOOP_BACKWARD, {offset = 0.5, playback_rate = 1.2}, complete_function)
	-- rive.cancel("/go2#rivemodel")

	msg.post(".", "acquire_input_focus")
end

function final(self)

end

function update(self, dt)

end

function fixed_update(self, dt)

end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.released then
		self.foo = self.foo or false
		if self.foo then
			rive.play_anim("/go2#rivemodel", "idle", go.PLAYBACK_LOOP_FORWARD, {offset = 0, playback_rate = 1 + math.random()}, complete_function)
		else
			rive.cancel("/go2#rivemodel")
		end
		self.foo = not self.foo
			
	end
	
end

function on_reload(self)

end
